feat(buildfab): v0.2.0, project add ci-pre-install, SAST tools add pvs-studio for open source projects

diff --git a/build/update-checking-actions.yml b/build/update-checking-actions.yml
--- a/build/update-checking-actions.yml
+++ b/build/update-checking-actions.yml
@@ -389,3 +389,30 @@ actions:
         exit 1
       fi
       echo "✅ cppcheck ${version} installed into ${install_prefix}/bin"
+
+  - name: check-pvs-studio
+    run: |
+      if ! which pvs-studio >/dev/null 2>&1; then
+        echo "pvs-studio is not installed."
+        exit 1
+      fi
+      pvs-studio --version
+
+  - name: install-pvs-studio
+    variants:
+    - when: ${{ platform == 'linux' && (os == "ubuntu" || os == "debian") }}
+      run: |
+       if ! which pvs -studio >/dev/null 2>&1; then
+         echo "pvs-studio is not installed."
+         wget -q -O - https://wcdn.pvs-studio.com/etc/pubkey.txt | apt-key add -
+         wget -O /etc/apt/sources.list.d/viva64.list https://wcdn.pvs-studio.com/etc/viva64.list
+         apt-get update
+         apt-get install pvs-studio
+         if ! which pws-studio >/dev/null 2>&1; then
+             echo "failed install pvs-studio"
+             exit 1
+         fi
+         exit 0
+       fi
+       echo "pvs-studio is already installed."
+       pvs-studio --version
